// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: logic/logic.proto

package logic

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type GateTologicMsgSerializeType int32

const (
	GateTologicMsg_None     GateTologicMsgSerializeType = 0
	GateTologicMsg_Json     GateTologicMsgSerializeType = 1
	GateTologicMsg_Protobuf GateTologicMsgSerializeType = 2
)

var GateTologicMsgSerializeType_name = map[int32]string{
	0: "None",
	1: "Json",
	2: "Protobuf",
}

var GateTologicMsgSerializeType_value = map[string]int32{
	"None":     0,
	"Json":     1,
	"Protobuf": 2,
}

func (x GateTologicMsgSerializeType) String() string {
	return proto.EnumName(GateTologicMsgSerializeType_name, int32(x))
}

func (GateTologicMsgSerializeType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_2dfb3aef05fe3328, []int{0, 0}
}

type GateTologicMsg struct {
	From                 int64                       `protobuf:"varint,1,opt,name=from,proto3" json:"from,omitempty"`
	ServerId             int64                       `protobuf:"varint,2,opt,name=serverId,proto3" json:"serverId,omitempty"`
	Serialize            GateTologicMsgSerializeType `protobuf:"varint,3,opt,name=serialize,proto3,enum=logic.GateTologicMsgSerializeType" json:"serialize,omitempty"`
	Data                 []byte                      `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *GateTologicMsg) Reset()         { *m = GateTologicMsg{} }
func (m *GateTologicMsg) String() string { return proto.CompactTextString(m) }
func (*GateTologicMsg) ProtoMessage()    {}
func (*GateTologicMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_2dfb3aef05fe3328, []int{0}
}
func (m *GateTologicMsg) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GateTologicMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GateTologicMsg.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GateTologicMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GateTologicMsg.Merge(m, src)
}
func (m *GateTologicMsg) XXX_Size() int {
	return m.Size()
}
func (m *GateTologicMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_GateTologicMsg.DiscardUnknown(m)
}

var xxx_messageInfo_GateTologicMsg proto.InternalMessageInfo

func (m *GateTologicMsg) GetFrom() int64 {
	if m != nil {
		return m.From
	}
	return 0
}

func (m *GateTologicMsg) GetServerId() int64 {
	if m != nil {
		return m.ServerId
	}
	return 0
}

func (m *GateTologicMsg) GetSerialize() GateTologicMsgSerializeType {
	if m != nil {
		return m.Serialize
	}
	return GateTologicMsg_None
}

func (m *GateTologicMsg) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_2dfb3aef05fe3328, []int{1}
}
func (m *Empty) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return m.Size()
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

func init() {
	proto.RegisterEnum("logic.GateTologicMsgSerializeType", GateTologicMsgSerializeType_name, GateTologicMsgSerializeType_value)
	proto.RegisterType((*GateTologicMsg)(nil), "logic.GateTologicMsg")
	proto.RegisterType((*Empty)(nil), "logic.empty")
}

func init() { proto.RegisterFile("logic/logic.proto", fileDescriptor_2dfb3aef05fe3328) }

var fileDescriptor_2dfb3aef05fe3328 = []byte{
	// 240 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0xcc, 0xc9, 0x4f, 0xcf,
	0x4c, 0xd6, 0x07, 0x93, 0x7a, 0x05, 0x45, 0xf9, 0x25, 0xf9, 0x42, 0xac, 0x60, 0x8e, 0xd2, 0x29,
	0x46, 0x2e, 0x3e, 0xf7, 0xc4, 0x92, 0xd4, 0x90, 0x7c, 0x30, 0xdf, 0xb7, 0x38, 0x5d, 0x48, 0x88,
	0x8b, 0x25, 0xad, 0x28, 0x3f, 0x57, 0x82, 0x51, 0x81, 0x51, 0x83, 0x39, 0x08, 0xcc, 0x16, 0x92,
	0xe2, 0xe2, 0x28, 0x4e, 0x2d, 0x2a, 0x4b, 0x2d, 0xf2, 0x4c, 0x91, 0x60, 0x02, 0x8b, 0xc3, 0xf9,
	0x42, 0x8e, 0x5c, 0x9c, 0xc5, 0xa9, 0x45, 0x99, 0x89, 0x39, 0x99, 0x55, 0xa9, 0x12, 0xcc, 0x0a,
	0x8c, 0x1a, 0x7c, 0x46, 0xca, 0x7a, 0x10, 0xab, 0x50, 0x4d, 0xd6, 0x83, 0x2b, 0x0b, 0xa9, 0x2c,
	0x48, 0x0d, 0x42, 0xe8, 0x02, 0x59, 0x99, 0x92, 0x58, 0x92, 0x28, 0xc1, 0xa2, 0xc0, 0xa8, 0xc1,
	0x13, 0x04, 0x66, 0x2b, 0x19, 0x72, 0xf1, 0xa2, 0xa8, 0x17, 0xe2, 0xe0, 0x62, 0xf1, 0xcb, 0xcf,
	0x4b, 0x15, 0x60, 0x00, 0xb1, 0xbc, 0x8a, 0xf3, 0xf3, 0x04, 0x18, 0x85, 0x78, 0xb8, 0x38, 0x02,
	0x40, 0xde, 0x49, 0x2a, 0x4d, 0x13, 0x60, 0x52, 0x62, 0xe7, 0x62, 0x4d, 0xcd, 0x2d, 0x28, 0xa9,
	0x34, 0xb2, 0xe6, 0x62, 0xf5, 0x01, 0x59, 0x2a, 0x64, 0xc4, 0xc5, 0x0d, 0x71, 0x03, 0x84, 0x2b,
	0x8a, 0xd5, 0x5d, 0x52, 0x3c, 0x50, 0x61, 0xb0, 0x66, 0x27, 0xd1, 0x13, 0x8f, 0xe4, 0x18, 0x2f,
	0x3c, 0x92, 0x63, 0x7c, 0xf0, 0x48, 0x8e, 0x31, 0x8a, 0x5d, 0x0f, 0x12, 0x6c, 0x49, 0x6c, 0xe0,
	0x70, 0x33, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0x5c, 0x3e, 0x6d, 0xe9, 0x4c, 0x01, 0x00, 0x00,
}

func (m *GateTologicMsg) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GateTologicMsg) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GateTologicMsg) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if len(m.Data) > 0 {
		i -= len(m.Data)
		copy(dAtA[i:], m.Data)
		i = encodeVarintLogic(dAtA, i, uint64(len(m.Data)))
		i--
		dAtA[i] = 0x22
	}
	if m.Serialize != 0 {
		i = encodeVarintLogic(dAtA, i, uint64(m.Serialize))
		i--
		dAtA[i] = 0x18
	}
	if m.ServerId != 0 {
		i = encodeVarintLogic(dAtA, i, uint64(m.ServerId))
		i--
		dAtA[i] = 0x10
	}
	if m.From != 0 {
		i = encodeVarintLogic(dAtA, i, uint64(m.From))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *Empty) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Empty) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Empty) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	return len(dAtA) - i, nil
}

func encodeVarintLogic(dAtA []byte, offset int, v uint64) int {
	offset -= sovLogic(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *GateTologicMsg) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.From != 0 {
		n += 1 + sovLogic(uint64(m.From))
	}
	if m.ServerId != 0 {
		n += 1 + sovLogic(uint64(m.ServerId))
	}
	if m.Serialize != 0 {
		n += 1 + sovLogic(uint64(m.Serialize))
	}
	l = len(m.Data)
	if l > 0 {
		n += 1 + l + sovLogic(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *Empty) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func sovLogic(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozLogic(x uint64) (n int) {
	return sovLogic(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *GateTologicMsg) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowLogic
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GateTologicMsg: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GateTologicMsg: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field From", wireType)
			}
			m.From = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLogic
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.From |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ServerId", wireType)
			}
			m.ServerId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLogic
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ServerId |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Serialize", wireType)
			}
			m.Serialize = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLogic
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Serialize |= GateTologicMsgSerializeType(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Data", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLogic
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthLogic
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthLogic
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Data = append(m.Data[:0], dAtA[iNdEx:postIndex]...)
			if m.Data == nil {
				m.Data = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipLogic(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthLogic
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthLogic
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Empty) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowLogic
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: empty: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: empty: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipLogic(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthLogic
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthLogic
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipLogic(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowLogic
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowLogic
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowLogic
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthLogic
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupLogic
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthLogic
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthLogic        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowLogic          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupLogic = fmt.Errorf("proto: unexpected end of group")
)
